version: '3.8'

services:
  pom-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.production
    restart: always

  # Development service
  pom-web-dev:
    build:
      context: ..
      target: deps
      dockerfile: docker/Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env.development
    restart: always 